const Types = {
    INITIALIZE_GLOBAL_STATE: 'INITIALIZE_GLOBAL_STATE',
    SET_GLOBAL_STATE: 'SET_GLOBAL_STATE',
    SAVE_API_TOKEN: 'SAVE_API_TOKEN',
    REMOVE_API_TOKEN: 'REMOVE_API_TOKEN',
};

export default Types;